### PR TITLE
Use additional instructions for generating book

### PR DESCRIPTION
**Pull request by Mustafa-Esoofally**
Now you can add custom instructions to fine-tune your book's content and structure.  Want more historical examples? Need a focus on beginner concepts? Just tell the AI!

### CODE REVIEW

**Comment by Bklieger** [comment]
Exciting work! Thank you for your contributions on this PR. I've reviewed the changes and there is one minor issue which must be resolved before merging:

1. This branch has merge conflicts with main.py that must be resolved. Please pull the latest version of main.py from the repository and resolve the merge conflicts.

Once this has been updated, the code will be re-reviewed and merged.

**Review by Bklieger — CHANGES_REQUESTED** [review]
Exciting work! Thank you for your contributions on this PR. I've reviewed the changes and there is one minor issue which must be resolved before merging:

1. This branch has merge conflicts with main.py that must be resolved. Please pull the latest version of main.py from the repository and resolve the merge conflicts.

Once this has been updated, the code will be re-reviewed and merged.

**Comment by Mustafa-Esoofally** [comment]
Hey, I have resolved the merge conflicts

**Review by Bklieger — APPROVED** [review]
Code and new feature are fully functional.

**Comment by Mustafa-Esoofally** [comment]
Awesome! Firing off more PRs soon

**Pull request merged**
